### ISSUE TITLE
Cannot run samples involving records

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#531] opened 2020-06-11 18:34 UTC
Link: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKBuPIE4AKTOAdwAIAlOAYyfIBKAHQANQQG4aNAPQyOAWiXTqCPgHsEObnyYBLTDA7iptapghg4UAA4RecDvWFcsMPVeEBhdWBt6AG0QAZUQANz0HKA4AbydSDgBJKABRAA94BAsAxMw9IziAXw5CoA===

Error message: Unbreakable.AssemblyGuardException: Method System.Void Rec::Deconstruct(System.Int32&) performs pointer operations which cannot be validated.

Sample code:
```cs
using System;

Console.WriteLine(new Rec(1).X);

// ---

record Rec(int X);

namespace System.Runtime.CompilerServices { class IsExternalInit { } }
```

This probably happens because records with parameter lists synthesize a `Deconstruct` method. Is there any way the restriction can be modified to make it possible to run some record samples?

**Comment by ashmind** [comment] 2020-07-05 00:09
Thanks for reporting! I might be able to validate this, I'll take a look (no timeline promises though).

**Comment by RikkiGibson** [comment] 2020-09-07 19:19
Please let me know if there's any way I can help fix this :)

**Comment by ashmind** [comment] 2020-09-10 04:20
I was going to write some thoughts on help, but then I realized it would be more interesting to write a fix instead, so it's fixed now :)

**Comment by RikkiGibson** [comment] 2020-09-10 13:59
No sweat 😉 and thank you for all your work on this invaluable tool.

**Comment by Kryptos-FR** [comment] 2020-10-01 13:15
It seems to be happening again.

Link: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMAjALABQuADAAS6EAsA3GWbgMxUJwDGA9ggCZUAMjwDmAS0wAlOFB7oEXOAApa1AKpREmCGDhIahagAVoUAO59+B4Dx4AbKjL1hgiALJwAlGQDeZAF9mUh09KAAHCCVDADopLBhxPRiAYR4wcPF7RABlRAA3cSUoPzIqGnwqAEkoAFEAD3gEHXsqzHEYKl8qINJelnYCQwB2UtJy8rZDADYaOip3CEllHJgESVEAbQBdKggEUSgfcYn/E4mJ/P29qgBeKkw4c2ExSRk5BSVlACIAKR4ABaYb4Gb4AER4cBBVDW6G8DAuFzKE16ASAA

**Comment by ashmind** [comment] 2020-12-16 07:08
Interesting! I will take a look when I have a moment.

**Comment by ashmind** [comment] 2021-11-13 07:20
Hi @Kryptos-FR, I didn't have a chance to take a look at the root cause, however this has been resolved by moving to a new Run model.

**Closed by ashmind** 2021-11-13 07:20 UTC
Labels: ✔ pushed to edge, external:unbreakable
