### ISSUE TITLE
sharplab.io currently down

### ISSUE THREAD

**Issue by colgreen** [ashmind/SharpLab#602] opened 2021-03-28 11:05 UTC
It was working about 12 hours ago...

(current time 2021-03-28 11:05:00 UTC)

```
HTTP Error 500.32 - ANCM Failed to Load dll
Common solutions to this issue:
The application was likely published for a different bitness than w3wp.exe/iisexpress.exe is running as.
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028526
```

**Comment by ashmind** [comment] 2021-03-28 17:56
Thanks for reporting! Restarted, working now. Will have to investigate the root cause, so I'll leave this open for now.

**Comment by ashmind** [comment] 2021-03-29 08:25
Applied autoheal policy -- assuming this is fully resolved now, closing.

**Closed by ashmind** 2021-03-29 08:25 UTC
