### ISSUE TITLE
init only properties don't work run mode. 

### ISSUE THREAD

**Issue by jaredpar** [ashmind/SharpLab#574] opened 2020-10-29 18:53 UTC
Consider the following code:

```cs
using System;

var c = new C()
{
    Value = 42,
};
Console.WriteLine(c.Value);

class C
{
    public int Value { get; init; }
}

namespace System.Runtime.CompilerServices
{
    public class IsExternalInit { }
}
```

This is a pretty straight forward case of using a C# 9 `init` only property. This sample will run just fine on `netcoreapp3.1`, `net5.0` or `net472` but it will fail in sharplab with the following error:

```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at C.set_Value(Int32 value)
   at <Program>$.<Main>$(String[] args)
```

The IL produced here is not verifiable due to the way the `set` accessor is generated. If the program was run under .NET Framework in a manner that required verifiable assemblies (say running in full trust mode) I would expect that type of error to happen. Is that what's going on here or is something else happening?

[Example Repro](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKBpoDcIEACAY2YF5nM4B3ZgMIAKAJQ0A3jWbTmANQgAbdHE7MALKSQ0AvgG4axcgE4hrAHTylcEftrUygiVJnEAzMwCWmGHMXLm4swA5nAwup6YHmHM2jp01JgQYHBQAA4QrCqGZgBKWDAeyWYCAPZgqR4KiADKiPQemVBO1DLMbm2kzACSUACiAB7wCIkKXZE+gbHUU0A===)

**Comment by ashmind** [comment] 2020-12-16 07:30
Thanks for reporting! This is likely caused by one of two layers of IL rewriting I am doing -- they are not used to init properties yet, so likely rewrite something wrong. I will review this when I have a moment.

**Comment by jaredpar** [comment] 2020-12-16 15:51
Didn't realize that you were doing a lot of IL rewriting here. 

One quirk I will point out that may be relevant is that `init` properties in C# use a `modreq` on the property setter. That is technically a part of the signature and it's possible your rewrite isn't accounting for this properly.

**Comment by ashmind** [comment] 2021-01-03 06:42
This is now resolved in Default -- might take a bit of time to deploy to `master` and other Roslyn branches, but eventually will be there as well. So I'll close now.

Root cause was code failed to to detect `modreq`-wrapped void and assumed it needed to report the return value.
That unbalanced stack which did not have any return value.

**Closed by ashmind** 2021-01-03 06:42 UTC
Labels: :beetle: bug, ✔ pushed to edge
