### ISSUE TITLE
[JitGeneric(typeof(string))] causes ArgumentException

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#284] opened 2018-04-27 18:27 UTC
JIT asm for this code causes [System.ArgumentException: The given generic instantiation was invalid](https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABAZQAtEAnABwBlFgA6AJQFcA7OAS1QFMBuAWACh+AbQBSrOAHEOTDiVYBjABRwAnmQ4B7AGYLMARmwBKAwF1+mAMy5MAJlwBhADwAVAHz8A3vwC+/IA=):
```cs
using SharpLab.Runtime;

[JitGeneric(typeof(string))]
public class C<T>
{
}
```

Ironic, given this suggestion for `public class C<T>`:

```asm
    ; Open generics cannot be JIT-compiled.
    ; However you can use attribute SharpLab.Runtime.JitGeneric to specify argument types.
    ; Example: [JitGeneric(typeof(int)), JitGeneric(typeof(string))] void M<T>() { ... }.
```

**Comment by ashmind** [comment] 2018-04-27 21:32
Very interesting! No idea why. I'll research.

**Comment by svick** [comment] 2019-06-06 18:25
[It does seem to work on .Net Core.](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAIBlAC2ygAcAZbYAOgCUBXAOwwEt8MANwBYAFDiA2gCk+GAOIxuMKHzAAKDAE96MCADN1xAIykAlGYC644gGZyxAEzkAwgB4AKgD5xAb3EAvuJAA=)

Also, based on [this SO answer](https://stackoverflow.com/a/31754895/41071), I *think* the fix is to use the `PrepareMethod(RuntimeMethodHandle, RuntimeTypeHandle[])` overload, [whose documentation explains the issue](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimehelpers.preparemethod?view=netframework-4.8#System_Runtime_CompilerServices_RuntimeHelpers_PrepareMethod_System_RuntimeMethodHandle_System_RuntimeTypeHandle___):

> The common language runtime cannot prepare constrained execution regions (CERs) rooted in a method that has generic type parameters (either a type parameter on the class containing the method or one on the method itself) when those type parameters are instantiated as reference types.

**Comment by ashmind** [comment] 2019-10-13 07:23
I want to save some effort by not doing improvements in .NET Framework code, and this is not reproducible in .NET Core, so I'll close this as "cannot reproduce".

If you want it to be resolved in .NET Framework, please let me know, and I'll recreate as "up for grabs" .NET Framework-specific ticket.

**Closed by ashmind** 2019-10-13 07:23 UTC
Labels: :beetle: bug, area:jitdasm
